{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "CPULA",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "LA_1M"
    },
    {
     "expr": "node_load5{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "LA_5M"
    },
    {
     "expr": "node_load15{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}",
     "legendFormat": "LA_15M"
    }
   ]
  },
  {
   "title": "FREE RAM",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes{instance=\"nodeexporter:9100\",job=\"nodeexporter\"}"
    }
   ]
  },
  {
   "title": "CPU USAGE",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"nodeexporter\",mode=\"idle\"}[1m])) * 100)"
    }
   ]
  }
 ]
}